//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModulusChecking.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModulusChecking.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 938173 938017
        ///938289 938068
        ///938297 938076
        ///938600 938611
        ///938602 938343
        ///938604 938603
        ///938608 938408
        ///938609 938424
        ///938613 938017
        ///938616 938068
        ///938618 938657
        ///938620 938343
        ///938622 938130
        ///938628 938181
        ///938643 938246
        ///938647 938611
        ///938648 938246
        ///938649 938394
        ///938651 938335
        ///938653 938424
        ///938654 938621
        ///.
        /// </summary>
        public static string scsubtab {
            get {
                return ResourceManager.GetString("scsubtab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 010004 016715 MOD11    0    0    0    0    0    0    8    7    6    5    4    3    2    1
        ///040004 040004 DBLAL    0    0    0    0    0    0    8    7    6    5    4    3    2    1
        ///040010 040014 MOD11    0    0    0    0    0    0    0    7    6    5    4    3    2    1
        ///040010 040014 DBLAL    2    1    2    1    2    1    2    1    2    1    2    1    2    1
        ///040020 040059 MOD11    0    2    0    0    9    1    2    8    4    3    7    5    6    1
        ///040072 040073 MOD11    0    0    0    0    0    0    8    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string valacdos {
            get {
                return ResourceManager.GetString("valacdos", resourceCulture);
            }
        }
    }
}
